export { default as corner1 } from "$lib/assets/frame/corner-1.svg"
export { default as corner2 } from "$lib/assets/frame/corner-2.svg"
export { default as corner3 } from "$lib/assets/frame/corner-3.svg"
export { default as corner4 } from "$lib/assets/frame/corner-4.svg"
export { default as corner5 } from "$lib/assets/frame/corner-5.svg"
export { default as corner6 } from "$lib/assets/frame/corner-6.svg"
export { default as corner7 } from "$lib/assets/frame/corner-7.svg"
export { default as corner8 } from "$lib/assets/frame/corner-8.svg"
export { default as corner9 } from "$lib/assets/frame/corner-9.svg"
export { default as corner10 } from "$lib/assets/frame/corner-10.svg"
export { default as corner11 } from "$lib/assets/frame/corner-11.svg"
export { default as corner12 } from "$lib/assets/frame/corner-12.svg"
export { default as corner13 } from "$lib/assets/frame/corner-13.svg"
export { default as corner14 } from "$lib/assets/frame/corner-14.svg"

export { default as center1 } from "$lib/assets/frame/center1.svg"
export { default as center2 } from "$lib/assets/frame/center2.svg"
export { default as center3 } from "$lib/assets/frame/center3.svg"
export { default as center4 } from "$lib/assets/frame/center4.svg"

export { default as horz1 } from "$lib/assets/frame/horz1.svg"
export { default as horz2 } from "$lib/assets/frame/horz2.svg"
export { default as horz3 } from "$lib/assets/frame/horz3.svg"
export { default as horz4 } from "$lib/assets/frame/horz4.svg"

export { default as vert1 } from "$lib/assets/frame/vert1.svg"
export { default as vert2 } from "$lib/assets/frame/vert2.svg"
export { default as vert3 } from "$lib/assets/frame/vert3.svg"
export { default as vert4 } from "$lib/assets/frame/vert4.svg"